matrix:
    include:
        - language: smalltalk
          os:
              - linux
              - osx
          smalltalk:
              - Pharo32-7.0
              - Pharo64-7.0
              - Pharo32-8.0
              - Pharo64-8.0
        - language: bash
          os:
             - linux
             - osx
          before_script:
             - cd shell-tests
             - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx
             - wget https://raw.githubusercontent.com/juliendelplanque/shell-scripts/master/build_headless_image.sh
             - ARCHITECTURE=64 bash build_headless_image.sh "jpp" "github://juliendelplanque/jpp/src" "BaselineOfJSONPreprocessor" "core" 
          script:
             - bash jpp-tests.sh

notifications:
    email:
        on_success: never
        on_failure: always

